theme: jekyll-theme-minimal
title: James Chase
description: Computer Science Student & HealthTech Developer
show_downloads: false
google_analytics:
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
